// strings.h - generated from translations.csv by build.ps1. Do not hand-edit.
#pragma once

#define IDS_LOC_FIRST 1024
#define IDS_MENU_SHOW_SECONDS        1024
#define IDS_MENU_CUSTOMIZE           1025
#define IDS_MENU_RESIZE              1026
#define IDS_MENU_FACE                1027
#define IDS_MENU_TOPMOST             1028
#define IDS_MENU_STARTUP             1029
#define IDS_MENU_TRAY                1030
#define IDS_MENU_ABOUT               1031
#define IDS_MENU_EXIT                1032
#define IDS_CUSTOMIZE                1033
#define IDS_CUSTOMIZE_TITLE          1034
#define IDS_CUSTOMIZE_NOTHING        1035
#define IDS_RESET_FACE               1036
#define IDS_ABOUT_TITLE              1037
#define IDS_FEEDBACK                 1038
#define IDS_OTHER_APPS               1039
#define IDS_FLYPHOTOS_BLURB          1040
#define IDS_LETITRAIN_BLURB          1041
#define IDS_WTICK_BLURB              1042
#define IDS_DESKFLIP_BLURB           1043
#define IDS_FACE_SIMPLE              1044
#define IDS_FACE_CLASSIC_DARK        1045
#define IDS_FACE_CLASSIC_LIGHT       1046
#define IDS_FACE_MINIMAL             1047
#define IDS_FACE_ICON                1048
#define IDS_FACE_BOLD                1049
#define IDS_FACE_FLAT                1050
#define IDS_FACE_GLASS               1051
#define IDS_FACE_DOTS                1052
#define IDS_FACE_DIGITAL             1053
#define IDS_FACE_DIGITAL_BOLD        1054
#define IDS_FACE_WORD                1055
#define IDS_FACE_STACK               1056
#define IDS_FACE_TERMINAL            1057
#define IDS_FACE_BANNER              1058
#define IDS_FACE_SPLIT               1059
#define IDS_FACE_IMAGE               1060
#define IDS_OPT_HOUR24               1061
#define IDS_OPT_ACCENT_12            1062
#define IDS_OPT_ACCENT_COLOUR        1063
#define IDS_OPT_BLINK                1064
#define IDS_OPT_DATE_FORMAT          1065
#define IDS_OPT_DIAL_COLOUR          1066
#define IDS_OPT_DIGIT_COLOUR         1067
#define IDS_OPT_DOT_COUNT            1068
#define IDS_OPT_DOT_SIZE             1069
#define IDS_OPT_DROP_SHADOW          1070
#define IDS_OPT_FACE_COLOUR          1071
#define IDS_OPT_FROST                1072
#define IDS_OPT_HAND_COLOUR          1073
#define IDS_OPT_HOUR_BLOCK           1074
#define IDS_OPT_INK_COLOUR           1075
#define IDS_OPT_LABEL_COLOUR         1076
#define IDS_OPT_LIT_LETTER           1077
#define IDS_OPT_MARKING_COLOUR       1078
#define IDS_OPT_MINUTE_BLOCK         1079
#define IDS_OPT_MINUTE_DIMMING       1080
#define IDS_OPT_NUMERALS             1081
#define IDS_OPT_PANEL_COLOUR         1082
#define IDS_OPT_PHOSPHOR             1083
#define IDS_OPT_PLATE_COLOUR         1084
#define IDS_OPT_PLATE_SHAPE          1085
#define IDS_OPT_PROMPT               1086
#define IDS_OPT_RIM_COLOUR           1087
#define IDS_OPT_RING_COLOUR          1088
#define IDS_OPT_RING_THICKNESS       1089
#define IDS_OPT_SHOW_AMPM            1090
#define IDS_OPT_SHOW_DATE            1091
#define IDS_OPT_SHOW_MINUTE_DOTS     1092
#define IDS_OPT_SHOW_PANEL           1093
#define IDS_OPT_TEXT_COLOUR          1094
#define IDS_OPT_TICK_MARKS           1095
#define IDS_CHOICE_ALL_12            1096
#define IDS_CHOICE_QUARTERS          1097
#define IDS_CHOICE_NONE              1098
#define IDS_CHOICE_MINUTE            1099
#define IDS_CHOICE_HOUR              1100
#define IDS_CHOICE_THIN              1101
#define IDS_CHOICE_NORMAL_WIDTH      1102
#define IDS_CHOICE_THICK             1103
#define IDS_CHOICE_CLEAR             1104
#define IDS_CHOICE_FROSTED           1105
#define IDS_CHOICE_OPAQUE            1106
#define IDS_CHOICE_LONG_DATE         1107
#define IDS_CHOICE_SHORT_DATE        1108
#define IDS_CHOICE_SMALL             1109
#define IDS_CHOICE_NORMAL_SIZE       1110
#define IDS_CHOICE_LARGE             1111
#define IDS_CHOICE_ROUNDED           1112
#define IDS_CHOICE_SQUARE            1113
#define IDS_CHOICE_CIRCLE            1114
#define IDS_CHOICE_MATCH_HOUR        1115
#define IDS_CHOICE_DIM               1116
#define IDS_CHOICE_FAINT             1117
#define IDS_CHOICE_DOTS_4            1118
#define IDS_CHOICE_DOTS_12           1119
#define IDS_CHOICE_DOTS_60           1120
#define IDS_CHOICE_PROMPT_DOLLAR     1121
#define IDS_CHOICE_PROMPT_ANGLE      1122
#define IDS_CHOICE_PROMPT_PATH       1123
#define IDS_RIGHTS_RESERVED          1124
